services:
  undercover-app:
    container_name: undercover
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "24582:80"
      - "24583:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - undercover-app
